### ISSUE TITLE
Tests with py.test don't run

### ISSUE THREAD

**Issue by jkahn** [dib-lab/sourmash#10]
I draw several fatal errors when I try to run what seems like a reasonable thing here.

```
git clone {repo}/sourmash.git
cd sourmash
pip install . pytest matplotlib
py.test .
```
Here is the top few dozen lines of the error logs from doing that:
```
(sourmash)jeremy@anjou:~/src/sourmash (master *=)$ py.test .
============================= test session starts ==============================
platform linux2 -- Python 2.7.11, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/jeremy/src/sourmash, inifile: pytest.ini
collected 29 items / 1 errors 

doc/api-example.rst F
doc/api.rst s
doc/command-line.rst s
doc/index.rst s
doc/more-info.rst s
doc/requirements.rst s
sourmash_lib/__init__.py FFFFFFFF
sourmash_lib/signature.py FFFFFFFF
sourmash_lib/test_sourmash.py .FFFFFF

==================================== ERRORS ====================================
________________ ERROR collecting sourmash_lib/test__minhash.py ________________
sourmash_lib/test__minhash.py:39: in <module>
    from ._minhash import MinHash, hash_murmur
E   ImportError: No module named _minhash
=================================== FAILURES ===================================
________________________ [doctest] doc/api-example.rst _________________________
007 
008 Define two sequences:
009 
010 >>> seq1 = "ATGGCA"
011 >>> seq2 = "AGAGCA"
012 
013 Create two estimators using 3-mers, and add the sequences:
014 
015 >>> import sourmash_lib
016 >>> E1 = sourmash_lib.Estimators(n=20, ksize=3)
UNEXPECTED EXCEPTION: ImportError('cannot import name _minhash',)
Traceback (most recent call last):

  File "/usr/share/anaconda/anaconda2/envs/sourmash/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest api-example.rst[3]>", line 1, in <module>

  File "/home/jeremy/src/sourmash/sourmash_lib/__init__.py", line 27, in __init__
    from . import _minhash

ImportError: cannot import name _minhash

/home/jeremy/src/sourmash/doc/api-example.rst:16: UnexpectedException
________________________________ test_jaccard_1 ________________________________

    def test_jaccard_1():
>       E1 = Estimators(n=5, ksize=20)

```

**Comment by ctb** [comment]
Ahh!

You need to type 'make' first (or python setup.py build_ext -i).

All our instructions assume you've installed it with pip, which will run
setup.py automatically.

I will add developer instructions.

**Comment by jkahn** [comment]
I *did* install with pip, so is setup.py not doing enough?

**Comment by ctb** [comment]
fixed in latest!
