### ISSUE TITLE
Tests failed on shared server

### ISSUE THREAD

**Issue by erikyoung85** [dib-lab/sourmash#1007]
```
107 
108 ## Saving and loading signature files
109 
110 Signature files encapsulate MinHashes in JSON, and provide a way to
111 add some metadata to MinHashes.
112 
113 ```
114 >>> from sourmash import SourmashSignature, save_signatures
115 >>> sig1 = SourmashSignature(minhashes[0], name=genomes[0][:20])
116 >>> with open('/tmp/genome1.sig', 'wt') as fp:
UNEXPECTED EXCEPTION: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
 File "/home/eyoung85/miniconda3/envs/sourmash_dev/lib/python3.6/doctest.py", line 1330, in __run
  compileflags, 1), test.globs)
 File "<doctest api-example.md[23]>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: '/tmp/genome1.sig'
/home/eyoung85/sourmash/doc/api-example.md:116: UnexpectedException
```

**Comment by ctb** [comment]
note, this is on farm head node, and occurs because I ran the tests before him and so that file already exists with permissions that forbid him from overwriting it.

**Comment by ctb** [comment]
I think the right thing to do here is create either a guaranteed unique temporary directory (using mkdtemp?) or a random filename. Not sure which is cleanest; probably mkdtemp.

See the [tempfile module](https://docs.python.org/2/library/tempfile.html) in python.
