### ISSUE TITLE
`load_signatures` does not fail properly on non-existent file

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#1050]
In #1044, I discovered:

```
>>> import sourmash
>>> list(sourmash.load_signatures('xyz_dne', do_raise=True))
Error in parsing signature; quitting. Cannot open file or invalid signature
[]
```

**Comment by ctb** [comment]
Separately, the generator does not fail until it is asked for the first signature.
```
>>> sourmash.load_signatures('xyz_dne', quiet=True, do_raise=True)
<generator object load_signatures at 0x1015fc650>
>>> list(sourmash.load_signatures('xyz_dne', quiet=True, do_raise=True))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/t/dev/sourmash/sourmash/signature.py", line 265, in load_signatures  
    raise Exception("Error in parsing signature; quitting. Cannot open file or invalid signature")
Exception: Error in parsing signature; quitting. Cannot open file or invalid signature
```

**Comment by ctb** [comment]
The first can be fixed by modifying `load_signatures` like so:

```
    if input_type == SigInput.UNKNOWN:
        if not quiet:
            error("Error in parsing signature; quitting. Cannot open file or invalid signature")
        if do_raise:
            raise Exception("Error in parsing signature; quitting. Cannot open file or invalid signature")
```
