### ISSUE TITLE
sourmash compare fails when multiple signatures are in one file

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#123]
Original fastq files SRA accession:
ERR458584
ERR458585
ERR458586
ERR458587
ERR458588
ERR458589
ERR458590

Trimmed via khmer:
`$ trim-low-abund.py -k 21 -C 2 --variable-coverage --gzip /Users/yeast_raw_fastq/SNF2_BR13/*.fastq.gz`

With signatures generated by:
`$ sourmash compute -k 6 -o SNF2_BR13_k6_s1000 --track-abundance --scaled 1000 ./khmer_out/*abundtrim`

and compared with:
`$ sourmash compare -k 6 SNF2_BR13_k6_s1000\ copy -o trial_compare`

produces the following error:
`# running sourmash subcommand: compare
loading SNF2_BR13_k6_s1000 copy
Traceback (most recent call last):
  File "/Users/taylorreiter/anaconda/bin/sourmash", line 11, in <module>
    load_entry_point('sourmash==1.1', 'console_scripts', 'sourmash')()
  File "/Users/taylorreiter/anaconda/lib/python2.7/site-packages/sourmash_lib/__main__.py", line 973, in main
    SourmashCommands()
  File "/Users/taylorreiter/anaconda/lib/python2.7/site-packages/sourmash_lib/__main__.py", line 51, in __init__
    cmd(sys.argv[2:])
  File "/Users/taylorreiter/anaconda/lib/python2.7/site-packages/sourmash_lib/__main__.py", line 381, in compare
    loaded = list(loaded)
  File "/Users/taylorreiter/anaconda/lib/python2.7/site-packages/sourmash_lib/signature.py", line 179, in load_signatures
    ignore_md5sum=ignore_md5sum):
  File "/Users/taylorreiter/anaconda/lib/python2.7/site-packages/sourmash_lib/signature_json.py", line 214, in load_signatures_json
    for n, sigset in enumerate(it):
  File "/Users/taylorreiter/anaconda/lib/python2.7/site-packages/sourmash_lib/signature_json.py", line 190, in load_signatureset_json_iter
    prefix, event, value = next(parser)
  File "/Users/taylorreiter/anaconda/lib/python2.7/site-packages/ijson/common.py", line 65, in parse
    for event, value in basic_events:
  File "/Users/taylorreiter/anaconda/lib/python2.7/site-packages/ijson/backends/python.py", line 192, in basic_parse
    raise common.JSONError('Additional data')
ijson.common.JSONError: Additional data`

(File SNF2_BR13_k6_s1000 copy attached.)

When SNF2_BR13_k6_s1000 is split into its constituent parts, it runs fine:

`$ sourmash compare -k 6 ./*sig -o trial_compare2`

`# running sourmash subcommand: compare
loading ./SNF2_BR13_k6_s1000 copy_1.sig
loading ./SNF2_BR13_k6_s1000 copy_2.sig
loading ./SNF2_BR13_k6_s1000 copy_3.sig
loading ./SNF2_BR13_k6_s1000 copy_4.sig
loading ./SNF2_BR13_k6_s1000 copy_5.sig
loading ./SNF2_BR13_k6_s1000 copy_6.sig
loading ./SNF2_BR13_k6_s1000 copy_7.sig
0-./khmer_out/ERR458584.fastq.gz.abundtrim	[ 1.     0.377  0.454  0.475  0.761  0.702  0.473]
1-./khmer_out/ERR458585.fastq.gz.abundtrim	[ 0.377  1.     0.611  0.756  0.316  0.388  0.572]
2-./khmer_out/ERR458586.fastq.gz.abundtrim	[ 0.454  0.611  1.     0.45   0.293  0.277  0.908]
3-./khmer_out/ERR458587.fastq.gz.abundtrim	[ 0.475  0.756  0.45   1.     0.448  0.597  0.415]
4-./khmer_out/ERR458588.fastq.gz.abundtrim	[ 0.761  0.316  0.293  0.448  1.     0.694  0.331]
5-./khmer_out/ERR458589.fastq.gz.abundtrim	[ 0.702  0.388  0.277  0.597  0.694  1.     0.267]
6-./khmer_out/ERR458590.fastq.gz.abundtrim	[ 0.473  0.572  0.908  0.415  0.331  0.267  1.   ]
min similarity in matrix: 0.267350533666
saving labels to: trial_compare2.labels.txt
saving distance matrix to: trial_compare2`

Two *sig files are attached (file changed to .txt to enable uploading.)
[SNF2_BR13_k6_s1000 copy_1.txt](https://github.com/dib-lab/sourmash/files/724501/SNF2_BR13_k6_s1000.copy_1.txt)
[SNF2_BR13_k6_s1000 copy_2.txt](https://github.com/dib-lab/sourmash/files/724500/SNF2_BR13_k6_s1000.copy_2.txt)
[SNF2_BR13_k6_s1000 copy.txt](https://github.com/dib-lab/sourmash/files/724504/SNF2_BR13_k6_s1000.copy.txt)

**Comment by ctb** [comment]
thanks for the report! how did you generate these signatures?

**Comment by taylorreiter** [comment]
edited above!

**Comment by luizirber** [comment]
yikes, the signature file with multiple sigs is borked, we need a test for this...
