### ISSUE TITLE
Remove dependency on DISPLAY / X

### ISSUE THREAD

**Issue by mw55309** [dib-lab/sourmash#254]
So it turns out if you don't have X enabled / forwarded and $DISPLAY is not set, then nothing in sourmash works, even the functions that don't plan on plotting anything

**Comment by mw55309** [comment]
E.g.

~$ sourmash
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(sourmash:21985): Gdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "/usr/local/bin/sourmash", line 9, in <module>
    load_entry_point('sourmash==1.0', 'console_scripts', 'sourmash')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/sourmash_lib/__main__.py", line 10, in <module>
    from sourmash_lib import fig as sourmash_fig
  File "/usr/local/lib/python2.7/dist-packages/sourmash_lib/fig.py", line 8, in <module>
    import pylab
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.2-py2.7-linux-x86_64.egg/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.2-py2.7-linux-x86_64.egg/matplotlib/pylab.py", line 257, in <module>
    from matplotlib import cbook, mlab, pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.2-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.2-py2.7-linux-x86_64.egg/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.2-py2.7-linux-x86_64.egg/matplotlib/backends/backend_gtk3agg.py", line 11, in <module>
    from . import backend_gtk3
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.2-py2.7-linux-x86_64.egg/matplotlib/backends/backend_gtk3.py", line 54, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

**Comment by ctb** [comment]
Hi @mw55309,

if you do this:

echo 'backend : Agg' > matplotlibrc

it should disable that.  This is a known problem that I patch in our
latest tutorial,

https://sourmash.readthedocs.io/en/latest/tutorials.html

but hasn't made it into the issue tracker - thanks for submitting it!

---

I also note that you are using sourmash 1.0, I'd suggest updating to the
latest github master (see tutorial for instructions) as we are nearing
a release and the functionality has been vastly expanded.

Also, this problem should only crop up if you try to plot, in the 
more recent versions :).  (I was really confused at first because I
haven't run into this problem outside of plot for a while now!)

best,
--titus

**Comment by ctb** [comment]
This seems to no longer be an issue with newer matplotlib, but we should add to known issues.

**Comment by ctb** [comment]
closed by #419.
