### ISSUE TITLE
ValueError when ambiguous nucleotide

### ISSUE THREAD

**Issue by ctSkennerton** [dib-lab/sourmash#38]
I'm running `sourmash compute` on a number of read files and I get this error. Obviously one of the reads contains an `N`
```
Traceback (most recent call last):
  File "/home/cts/local/python34-virtualenv/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/home/cts/local/python34-virtualenv/lib/python3.4/site-packages/sourmash_lib/__main__.py", line 338, in main
    SourmashCommands()
  File "/home/cts/local/python34-virtualenv/lib/python3.4/site-packages/sourmash_lib/__main__.py", line 42, in __init__
    cmd(sys.argv[2:])
  File "/home/cts/local/python34-virtualenv/lib/python3.4/site-packages/sourmash_lib/__main__.py", line 151, in compute
    E.add_sequence(s, args.force)
  File "/home/cts/local/python34-virtualenv/lib/python3.4/site-packages/sourmash_lib/__init__.py", line 65, in add_sequence
    self.mh.add_sequence(seq, force)
ValueError: invalid DNA character in sequence: N
```

Is there a reason for throwing an error rather than simply dropping this kmer? I can get into the code to make changes but just wanted to know if this would affect the sketch too much?

**Comment by ctb** [comment]
-f will ignore invalid kmers.

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by bioinfonm** [comment]
I usually run with the -f flag so these errors don't come up. I am not sure what that will do to the sketch.

**Comment by ctSkennerton** [comment]
ah thanks

**Comment by ctb** [comment]
("Bad" k-mers are simply not hashed.)
