### ISSUE TITLE
ValueError: invalid DNA character in sequence: N

### ISSUE THREAD

**Issue by ljcohen** [dib-lab/sourmash#40]
Encountered error below with this command `sourmash compute --protein -k 18,21 /mnt/scratch/ljcohen/mmetsp_tmp/SRR1300520.left.fq.head`.  Looks like a problem with how  'N' are being handled?

```
(khmer_env)[ljcohen@dev-intel14 ~]$ sourmash compute --protein -k 18,21 /mnt/scratch/ljcohen/mmetsp_tmp/SRR1300520.left.fq.head
# running sourmash subcommand: compute
computing signatures for files: ['/mnt/scratch/ljcohen/mmetsp_tmp/SRR1300520.left.fq.head']
Computing signature for ksizes: [18, 21]
... reading sequences from /mnt/scratch/ljcohen/mmetsp_tmp/SRR1300520.left.fq.head
Traceback (most recent call last):
  File "/mnt/home/ljcohen/khmer_env/bin/sourmash", line 9, in <module>
    load_entry_point('sourmash==0.9.4', 'console_scripts', 'sourmash')()
  File "/mnt/home/ljcohen/khmer_env/lib/python2.7/site-packages/sourmash_lib/__main__.py", line 338, in main
    SourmashCommands()
  File "/mnt/home/ljcohen/khmer_env/lib/python2.7/site-packages/sourmash_lib/__main__.py", line 42, in __init__
    cmd(sys.argv[2:])
  File "/mnt/home/ljcohen/khmer_env/lib/python2.7/site-packages/sourmash_lib/__main__.py", line 151, in compute
    E.add_sequence(s, args.force)
  File "/mnt/home/ljcohen/khmer_env/lib/python2.7/site-packages/sourmash_lib/__init__.py", line 65, in add_sequence
    self.mh.add_sequence(seq, force)
ValueError: invalid DNA character in sequence: N
```

**Comment by bioinfonm** [comment]
Have you tried running with the -f flag?

**Comment by ljcohen** [comment]
Ha, works now - thank you @bioinfonm !

**Comment by bioinfonm** [comment]
You are welcome @ljcohen !
