### ISSUE TITLE
compile error on sourmash install

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#474]
On installing sourmash via `pip install .../master.zip` on mac OS sierra (10.13.3), the following error is thrown:

```
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/phi/miniconda3/envs/lab/include -I/Users/phi/miniconda3/envs/lab/include -I./sourmash -I./third-party/smhasher/ -I/Users/phi/miniconda3/envs/lab/include/python3.6m -c sourmash/_minhash.cpp -o build/temp.macosx-10.9-x86_64-3.6/sourmash/_minhash.o -std=c++11 -pedantic -arch x86_64 -mmacosx-version-min=10.7 -stdlib=libc++
    gcc: error: unrecognized command line option '-stdlib=libc++'
    error: command 'gcc' failed with exit status 1
```

This is because the current "default mac gcc" [does not have](https://github.com/explosion/spaCy/issues/237) a flag `-stdlib`.

Downloading the zip and removing `'-stdlib=libc++'` in `setup.py` from the following lines

```python
    EXTRA_COMPILE_ARGS.extend(['-arch', 'x86_64', '-mmacosx-version-min=10.7',
                               '-stdlib=libc++'])
```

solves this:

``` 
Successfully installed sourmash-2.0.0a6
```

**Comment by phiweger** [comment]
But then it doesn't solve the issue:


```bash
sourmash compute -k 21 -n 1000 example.fa -o example.sig.json

Traceback (most recent call last):
  File "/Users/phi/miniconda3/envs/lab/bin/sourmash", line 7, in <module>
    from sourmash.__main__ import main
  File "/Users/phi/miniconda3/envs/lab/lib/python3.6/site-packages/sourmash/__init__.py", line 10, in <module>
    from ._minhash import (MinHash, get_minhash_default_seed, get_minhash_max_hash)
ImportError: dlopen(/Users/phi/miniconda3/envs/lab/lib/python3.6/site-packages/sourmash/_minhash.cpython-36m-darwin.so, 2): Symbol not found: __ZSt24__throw_out_of_range_fmtPKcz
  Referenced from: /Users/phi/miniconda3/envs/lab/lib/python3.6/site-packages/sourmash/_minhash.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/phi/miniconda3/envs/lab/lib/python3.6/site-packages/sourmash/_minhash.cpython-36m-darwin.so
 ```

The problem seems to be in `setup.py` not being sure which `gcc` to invoke. See [here](https://stackoverflow.com/questions/28641408/how-to-tell-which-compiler-will-be-invoked-for-a-python-c-extension-in-setuptool) on this switch.

**Comment by ctb** [comment]
hi @phiweger is this still a problem?
