### ISSUE TITLE
Error pip install --pre sourmash

### ISSUE THREAD

**Issue by EileenNeelie** [dib-lab/sourmash#534]
Hi there,

I want to use souremash, however already when running pip install --pre sourmash I get the following error:

Collecting sourmash
  Using cached https://files.pythonhosted.org/packages/f3/c8/a921e25e90cc8e9bdf75931ac74d8460eb2791155f90f109923908015b13/sourmash-2.0.0a9.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /private/tmp/pip-build-a8DjqC/sourmash/.eggs/setuptools-40.2.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-a8DjqC/sourmash/setup.py", line 87, in <module>
        setup(**SETUP_METADATA)
      File "/macqiime/anaconda/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/macqiime/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/dist.py", line 268, in __init__
      File "/macqiime/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/dist.py", line 313, in fetch_build_eggs
      File "/macqiime/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 830, in resolve
      File "/macqiime/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 1068, in best_match
      File "/macqiime/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 705, in find
    pkg_resources.VersionConflict: (Cython 0.22 (/macqiime/anaconda/lib/python2.7/site-packages), Requirement.parse('Cython>=0.25.2'))
    
    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-a8DjqC/sourmash**

Any ideas what I am doing wrong or what I can do to resolve this?

Thank you!

**Comment by ctb** [comment]
hi, it looks like you need to upgrade Cython - and that the version you
need to upgrade to (0.25.2) is in conflict with the version that Qiime
needs (0.22).

Since you're using anaconda, you could create a new conda environment
that doesn't have qiime in it.  Alternatively, you could try
doing 'conda install sourmash' and see what happens :)

Creating a new conda environment should look something like this:

% conda create -n sourmash python=2.7 anaconda sourmash

(although you could also use python=3.6 with sourmash)

best,
--titus
