### ISSUE TITLE
sourmash signature rename behavior

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#619]
I think the behavior of `sourmash signature rename` is unintuitive. I would like if it would rename all MinHashes (i.e., k21,31,51) within a signature at once. When I try to run the command without a k-size specified, I get an error (see below).

If this is not possible, I think that the documentation should be more clear about the behavior of `rename`. 

---

When I use `sourmash signature rename` as follows:

```
sourmash signature rename -o ERR458584.khmer2.sig ERR458584.khmer.sig x
```

I get the following error:
```
Traceback (most recent call last):
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/lib/python3.6/site-packages/sourmash/__main__.py", line 82, in main
    cmd(sys.argv[2:])
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/lib/python3.6/site-packages/sourmash/sig/__main__.py", line 716, in main
    cmd(sysv_args[1:])
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/lib/python3.6/site-packages/sourmash/sig/__main__.py", line 426, in rename
    sigobj = sourmash.load_one_signature(args.signature, ksize=args.ksize, select_moltype=moltype)
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/lib/python3.6/site-packages/sourmash/signature.py", line 253, in load_one_signature
    raise ValueError("expected to load exactly one signature")
ValueError: expected to load exactly one signature
```

**Comment by taylorreiter** [comment]
I would also like to overwrite the original signature with the output. Currently, if I use the same name for the input and output signature, I get this error:

```
$ sourmash signature rename -k 31 -o ERR458584.khmer.sig ERR458584.khmer.sig ERR458584.khmer
Error in parsing signature; quitting.
Exception: Incomplete JSON data
Traceback (most recent call last):
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/lib/python3.6/site-packages/sourmash/signature.py", line 244, in load_one_signature
    first_sig = next(sigiter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/lib/python3.6/site-packages/sourmash/__main__.py", line 82, in main
    cmd(sys.argv[2:])
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/lib/python3.6/site-packages/sourmash/sig/__main__.py", line 716, in main
    cmd(sysv_args[1:])
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/lib/python3.6/site-packages/sourmash/sig/__main__.py", line 426, in rename
    sigobj = sourmash.load_one_signature(args.signature, ksize=args.ksize, select_moltype=moltype)
  File "/Users/taylorreiter/miniconda3/envs/sourmash_test/lib/python3.6/site-packages/sourmash/signature.py", line 246, in load_one_signature
    raise ValueError("no signatures to load")
ValueError: no signatures to load
```

My original signature also becomes 0B.

**Comment by ctb** [comment]
Seems reasonable :). Fixed in #620.
