### ISSUE TITLE
undefined symbol: yajl_version

### ISSUE THREAD

**Issue by jon-xu** [dib-lab/sourmash#652]
Hello, I am installing sourmash on CentOS6, under the created sourmash conda environment.
The conda install sourmash went well but after installation, when I try sourmash, below errors popped up:

Traceback (most recent call last):
  File "/home/jun.xu/jon/app/anaconda3/bin/sourmash", line 7, in <module>
    from sourmash.__main__ import main
  File "/home/jun.xu/jon/app/anaconda3/lib/python3.6/site-packages/sourmash/__init__.py", line 14, in <module>
    from .signature import (load_signatures, load_one_signature, SourmashSignature,
  File "/home/jun.xu/jon/app/anaconda3/lib/python3.6/site-packages/sourmash/signature.py", line 13, in <module>
    from . import signature_json
  File "/home/jun.xu/jon/app/anaconda3/lib/python3.6/site-packages/sourmash/signature_json.py", line 14, in <module>
    import ijson.backends.yajl2 as ijson
  File "/home/jun.xu/jon/app/anaconda3/lib/python3.6/site-packages/ijson/backends/yajl2.py", line 12, in <module>
    yajl = backends.find_yajl_ctypes(2)
  File "/home/jun.xu/jon/app/anaconda3/lib/python3.6/site-packages/ijson/backends/__init__.py", line 29, in find_yajl_ctypes
    require_version(yajl.yajl_version(), required)
  File "/home/jun.xu/jon/app/anaconda3/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/jun.xu/jon/app/anaconda3/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib64/libyajl.so.1: undefined symbol: yajl_version

Thanks for any help!
Jon

**Comment by jaybake5** [comment]
Hi, I'm having the same issue:

$ sourmash compute -h
Traceback (most recent call last):
  File "/home/jobaker/.conda/envs/sourmash_env/bin/sourmash", line 7, in <module>
    from sourmash.__main__ import main
  File "/home/jobaker/.conda/envs/sourmash_env/lib/python3.6/site-packages/sourmash/__init__.py", line 14, in <module>
    from .signature import (load_signatures, load_one_signature, SourmashSignature,
  File "/home/jobaker/.conda/envs/sourmash_env/lib/python3.6/site-packages/sourmash/signature.py", line 13, in <module>
    from . import signature_json
  File "/home/jobaker/.conda/envs/sourmash_env/lib/python3.6/site-packages/sourmash/signature_json.py", line 14, in <module>
    import ijson.backends.yajl2 as ijson
  File "/home/jobaker/.conda/envs/sourmash_env/lib/python3.6/site-packages/ijson/backends/yajl2.py", line 12, in <module>
    yajl = backends.find_yajl_ctypes(2)
  File "/home/jobaker/.conda/envs/sourmash_env/lib/python3.6/site-packages/ijson/backends/__init__.py", line 29, in find_yajl_ctypes
    require_version(yajl.yajl_version(), required)
  File "/home/jobaker/.conda/envs/sourmash_env/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/jobaker/.conda/envs/sourmash_env/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib64/libyajl.so.1: undefined symbol: yajl_version

Any idea what the problem is?
Thanks!

**Comment by jolespin** [comment]
This fixed the problem for me: 
`conda install -c conda-forge yajl`

**Comment by luizirber** [comment]
I'll update the bioconda recipe to bring `yajl` as a dependency, thanks @jolespin!

Does that fix the issue for you @jaybake5 @jon-xu ?

**Comment by jaybake5** [comment]
@jolespin and I work together, so it definitely fixed it for me, Thanks!

**Comment by luizirber** [comment]
@jaybake5 @jolespin  then thanks for having this discussion here, so it gets fixed for other users too =]

New package is up in bioconda, should bring `yajl` during installation.
