### ISSUE TITLE
LCA assertion error

### ISSUE THREAD

**Issue by tenguzame** [dib-lab/sourmash#653]
Greetings,
I'm trying to use sourmash to classify some genome bins. When I run the sourmash lca classify command using the precomputed LCA database, I keep getting the following error:
`Traceback (most recent call last):n/Windows/genbank-k31.lca.json
  File "/home/szn/miniconda3/envs/sourmash_env/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/home/szn/miniconda3/envs/sourmash_env/lib/python3.6/site-packages/sourmash/__main__.py", line 77, in main
    cmd(sys.argv[2:])
  File "/home/szn/miniconda3/envs/sourmash_env/lib/python3.6/site-packages/sourmash/lca/__main__.py", line 54, in main
    cmd(sysv_args[1:])
  File "/home/szn/miniconda3/envs/sourmash_env/lib/python3.6/site-packages/sourmash/lca/command_classify.py", line 117, in classify
    dblist, ksize, scaled = lca_utils.load_databases(args.db, args.scaled)
  File "/home/szn/miniconda3/envs/sourmash_env/lib/python3.6/site-packages/sourmash/lca/lca_utils.py", line 282, in load_databases
    lca_db.load(db_name)
  File "/home/szn/miniconda3/envs/sourmash_env/lib/python3.6/site-packages/sourmash/lca/lca_utils.py", line 162, in load
    assert version == '1.0'
AssertionError
`
What am I doing wrong?
Best regards

**Comment by ctb** [comment]
Hi, what version of sourmash are you using, do you know? You can get it by typing `sourmash info`.  Thanks!

**Comment by ctb** [comment]
Closing until there's an update.
