### ISSUE TITLE
sourmash lca classify does not write file

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#906]
In sourmash version 3.2.2, with command
```
for infile in *sig 
do
    sourmash lca classify --db ../../../genbank-k21.lca.json.gz --query ${infile} -o ${infile}.lca_class_k21.csv
done
```

Get the following error:
```
Traceback (most recent call last):
  File "/home/tereiter/miniconda3/envs/ibd/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/home/tereiter/miniconda3/envs/ibd/lib/python3.7/site-packages/sourmash/__main__.py", line 14, in main
    return mainmethod(args)
  File "/home/tereiter/miniconda3/envs/ibd/lib/python3.7/site-packages/sourmash/cli/lca/classify.py", line 30, in main
    return sourmash.lca.command_classify.classify(args)
  File "/home/tereiter/miniconda3/envs/ibd/lib/python3.7/site-packages/sourmash/lca/command_classify.py", line 116, in classify
    csvfp.writerow(['ID','status'] + list(lca_utils.taxlist()))
ValueError: I/O operation on closed file.
```

**Comment by taylorreiter** [comment]
with the `-o` parameter removed, the command runs as expected

**Comment by ctb** [comment]
fixed in master; see #900

**Comment by taylorreiter** [comment]
whoops, thanks!

**Comment by taylorreiter** [comment]
For the time being I rolled back to version 3.0.1 on conda and this now works :) I could have installed from master but...conda.
