### ISSUE TITLE
(Ignored) exception when overwriting sbt file

### ISSUE THREAD

**Issue by bluegenes** [dib-lab/sourmash#997]
When overwriting a zipped sbt with `sbt.save(sbt_file)`- either with a new one, or loading and adding to the existing sbt, I get an ignored exception. 

Looks like is show up when different signatures would be added to the file that clash with sigs in the existing file. Looking into `sbt_storage.py`, it seems that this might be coming from https://github.com/dib-lab/sourmash/blob/master/sourmash/sbt_storage.py#L209-L231. 

I think this happens because the default behavior is to add to the existing sbt file if possible? But if attributes are conflicting (e.g. duplicates as in #994), the old sigs are discarded and the new ones are written.

I can reproduce the exception by generating signatures with different attributes, and then attempting to overwrite the same file. The first couple examples below show cases where the exception is not triggered.

The following were run in succession:

**initial sbt generation**
```
sbt = sourmash.create_sbt_index()
mh = sourmash.MinHash(ksize=7, n=0, scaled=1, track_abundance=True, is_protein=True)
mh.add_sequence("MKVIRVG")
sig = sourmash.SourmashSignature(mh, name="test")
print("md5: " + sig.md5sum())
print(mh.get_mins())
leaf = sourmash.sbtmh.SigLeaf(sig.md5sum(), sig)
sbt.add_node(leaf)
sbt.save("test.sbt.zip")
```
output:
```
md5: 50e21312d5884ba6cb04967c6f19fd73
[10582183533110864607]

Finished saving nodes, now saving SBT json file.

Finished saving SBT, available at /home/ntpierce/2020-gtdb-smash/test.sbt.zip
```

**attempt to overwrite with exactly the same signature**
```
sbt = sourmash.create_sbt_index()
mh = sourmash.MinHash(ksize=7, n=0, scaled=1, track_abundance=True, is_protein=True)
mh.add_sequence("MKVIRVG")
sig = sourmash.SourmashSignature(mh, name="test")
print("md5: " + sig.md5sum())
print(sig.minhash.get_mins())
leaf = sourmash.sbtmh.SigLeaf(sig.md5sum(), sig)
sbt.add_node(leaf)
sbt.save("test.sbt.zip")
```
output:
```
md5: 50e21312d5884ba6cb04967c6f19fd73
[10582183533110864607]

Finished saving nodes, now saving SBT json file.

Finished saving SBT, available at /home/ntpierce/2020-gtdb-smash/test.sbt.zip
```

**compared to previous: different sequence (same name)**

```
sbt = sourmash.create_sbt_index()
mh = sourmash.MinHash(ksize=7, n=0, scaled=1, track_abundance=True, is_protein=True)
mh.add_sequence("VGLGDRG")
sig = sourmash.SourmashSignature(mh, name="test")
print("md5: " + sig.md5sum())
print(mh.get_mins())
leaf = sourmash.sbtmh.SigLeaf(sig.md5sum(), sig)
sbt.add_node(leaf)
sbt.save("test.sbt.zip")
```
output:
```
md5: 50e21312d5884ba6cb04967c6f19fd73
[10582183533110864607]

Finished saving nodes, now saving SBT json file.

Finished saving SBT, available at /home/ntpierce/2020-gtdb-smash/test.sbt.zip
```
Note: if using `add_protein`, this example has a different md5sum than the previous and triggers the exception.

**Compared to previous: same sequence sequence, different name**
```
sbt = sourmash.create_sbt_index()
mh = sourmash.MinHash(ksize=7, n=0, scaled=1, track_abundance=True, is_protein=True)
mh.add_sequence("VGLGDRG")
sig = sourmash.SourmashSignature(mh, name="test2")
print("md5: " + sig.md5sum())
print(mh.get_mins())
leaf = sourmash.sbtmh.SigLeaf(sig.md5sum(), sig)
sbt.add_node(leaf)
sbt.save("test.sbt.zip")
```
output:
```
md5: 50e21312d5884ba6cb04967c6f19fd73
[10582183533110864607]

Finished saving nodes, now saving SBT json file.
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x1501fb33d290>
Traceback (most recent call last):
  File "/home/ntpierce/miniconda3/envs/forage-env/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/ntpierce/miniconda3/envs/forage-env/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpcxjcz93i'

Finished saving SBT, available at /home/ntpierce/2020-gtdb-smash/test.sbt.zip
```

**compared to previous: longer sequence** 
```
sbt = sourmash.create_sbt_index()
mh = sourmash.MinHash(ksize=7, n=0, scaled=1, track_abundance=True, is_protein=True)
mh.add_sequence("MKVIRVGVVGLGDRGLH")
sig = sourmash.SourmashSignature(mh, name="test2")
print("md5: " + sig.md5sum())
print(sig.minhash.get_mins())
leaf = sourmash.sbtmh.SigLeaf(sig.md5sum(), sig)
sbt.add_node(leaf)
sbt.save("test.sbt.zip")
```
output:
```
md5: 50e21312d5884ba6cb04967c6f19fd73
[10582183533110864607]

Finished saving nodes, now saving SBT json file.
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x14bd03c0c290>
Traceback (most recent call last):
  File "/home/ntpierce/miniconda3/envs/forage-env/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/ntpierce/miniconda3/envs/forage-env/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpg5mzztem'

Finished saving SBT, available at /home/ntpierce/2020-gtdb-smash/test.sbt.zip
```

**compared to previous: same sequence and name (different ksize) = different md5**
```
sbt = sourmash.create_sbt_index()
mh = sourmash.MinHash(ksize=6, n=0, scaled=1, track_abundance=True, is_protein=True)
mh.add_sequence("MKVIRVGVVGLGDRGLH")
sig = sourmash.SourmashSignature(mh, name="test2")
print("md5: " + sig.md5sum())
print(mh.get_mins())
leaf = sourmash.sbtmh.SigLeaf(sig.md5sum(), sig)
sbt.add_node(leaf)
sbt.save("test.sbt.zip")
```
output:
```
md5: 62ae63876c591717429af207fa6abb70
[10582183533110864607]

Finished saving nodes, now saving SBT json file.
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x1501fb33d290>
Traceback (most recent call last):
  File "/home/ntpierce/miniconda3/envs/forage-env/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/ntpierce/miniconda3/envs/forage-env/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5lwwqlig'

Finished saving SBT, available at /home/ntpierce/2020-gtdb-smash/test.sbt.zip
```

**Comment by ctb** [comment]
was this fixed in https://github.com/dib-lab/sourmash/pull/994?

**Comment by luizirber** [comment]
> was this fixed in #994?

No, different problem. This is related to re-using the same ZIP file without doing `sourmash index --append`, because `sourmash index` by default doesn't try to overwrite the ZIP file (it tries to re-use it).

A minimum test for triggering `FileNotFoundError` is running `sourmash index` twice with same parameters.

**Comment by nmb85** [comment]
Same error message, but with no sbt.zip file to overwite.

Command using v3.4.1rc1:
sourmash index -k 31 /data/ncbi/genomes/all/GCA/gca_genbank.sbt.zip /data/ncbi/genomes/all/GCA/000/001/215/GCA_000001215.4_Release_6_plus_ISO1_MT/GCA_000001215.4_Release_6_plus_ISO1_MT_genomic.sig --from-file /data/ncbi/genomes/all/GCA/gca_latest_genomic_sig_minus1.txt

Error msg:
loaded 754132 sigs; saving SBT under "/data/ncbi/genomes/all/GCA/gca_genbank.sbt.zip"
Finished saving nodes, now saving SBT index file.
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7fd247dc4670>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tempfile.py", line 580, in __del__
    self.close()
  File "/usr/lib/python3.8/tempfile.py", line 576, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_cfwuh9j'
Finished saving SBT index, available at /data/ncbi/genomes/all/GCA/gca_genbank.sbt.zip
